name: CI/CD Test

on:
    push:
      branches:
        - 'feature/**'
    schedule:
      - cron: '45 19 * * 1'   
      - cron: '0 0 * * 2' 
    workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Tests
        run: |
          npm test

  build_and_upload:
    runs-on: ubuntu-20.04
    needs: [test]

    steps:
    - name: Checkout git
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

    - name: QEMU
      uses: docker/setup-qemu-action@v3

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Generar imagen docker y push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: sebastian627/workflowp:latest